# Generated by Django 2.1.7 on 2019-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('assignment_status', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('job', models.CharField(max_length=74)),
                ('organization', models.CharField(max_length=80)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(max_length=59)),
                ('ministry', models.CharField(max_length=49)),
                ('ssn', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=34)),
                ('bank_branch', models.CharField(max_length=60)),
                ('account_number', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=46)),
                ('region', models.CharField(max_length=20)),
                ('ssn_exempt', models.CharField(max_length=1)),
                ('pupil_teacher_status', models.CharField(max_length=1)),
                ('teacher_trainee_status', models.CharField(max_length=1)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('phoneNumber2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=60)),
            ],
        ),
    ]
